# Generated by Django 2.1.7 on 2019-02-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Year', models.CharField(max_length=4)),
                ('Rated', models.CharField(max_length=5)),
                ('Released', models.CharField(max_length=255)),
                ('Runtime', models.CharField(max_length=12)),
                ('Genre', models.CharField(max_length=255)),
                ('Director', models.CharField(max_length=255)),
                ('Writer', models.CharField(max_length=1024)),
                ('Actors', models.CharField(max_length=255)),
                ('Plot', models.TextField()),
                ('Language', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Awards', models.TextField()),
                ('Poster', models.CharField(max_length=255)),
                ('Metascore', models.CharField(max_length=3)),
                ('imdbRating', models.CharField(max_length=4)),
                ('imdbVotes', models.CharField(max_length=255)),
                ('imdbID', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('DVD', models.CharField(max_length=255)),
                ('BoxOffice', models.CharField(max_length=255)),
                ('Production', models.CharField(max_length=255)),
                ('Website', models.CharField(max_length=255)),
                ('Response', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=255)),
                ('Value', models.CharField(max_length=255)),
                ('RatedMovie', models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie')),
            ],
        ),
    ]
