# Generated by Django 2.1.7 on 2019-02-20 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='RatedMovie',
        ),
        migrations.DeleteModel(
            name='MovieRating',
        ),
    ]
