# Generated by Django 2.1.7 on 2019-02-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190220_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierating',
            old_name='RatedMovie',
            new_name='MovieRatings',
        ),
    ]
