# Generated by Django 2.1.7 on 2019-02-20 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190220_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='MovieRatings',
        ),
        migrations.AddField(
            model_name='movierating',
            name='RatedMovie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie'),
        ),
    ]
