# Generated by Django 2.1.7 on 2019-02-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190220_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movierating',
            name='RatedMovie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie'),
        ),
    ]
