# Generated by Django 2.1.7 on 2019-02-20 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190220_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='RatedMovie',
        ),
        migrations.AddField(
            model_name='movierating',
            name='Movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie'),
            preserve_default=False,
        ),
    ]
