# Generated by Django 2.1.7 on 2019-02-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190220_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movierating',
            name='Movie',
        ),
    ]
