# Generated by Django 2.1.7 on 2019-02-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movierating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Ratings',
            field=models.CharField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movierating',
            name='Movie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='MovieRatings', to='movies.Movie'),
            preserve_default=False,
        ),
    ]
