# Generated by Django 2.1.7 on 2019-02-20 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20190220_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Ratings',
        ),
        migrations.AlterField(
            model_name='movierating',
            name='Movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Ratings', to='movies.Movie'),
        ),
    ]
