# Generated by Django 2.1.7 on 2019-02-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_auto_20190220_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movierating',
            old_name='Movie',
            new_name='Ratings',
        ),
    ]
