# Generated by Django 2.1.7 on 2019-02-21 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_moviecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviecomment',
            old_name='Movie',
            new_name='CommentedMovie',
        ),
    ]
