# Generated by Django 2.1.7 on 2019-02-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20190221_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecomment',
            name='CommentedMovie',
        ),
        migrations.AddField(
            model_name='moviecomment',
            name='CommentedMovieID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='CommentedMovieID', to='movies.Movie'),
            preserve_default=False,
        ),
    ]
