# Generated by Django 2.1.7 on 2019-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_auto_20190221_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomment',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
