# Generated by Django 2.1.7 on 2019-02-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_auto_20190222_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director',
            new_name='boxoffice',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_votes',
            new_name='imdbvotes',
        ),
    ]
